language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database trevis_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --path=MyProject/*/Infrastructure/Migrations/

script:
  - vendor/bin/phpunit

